const TYPE_APP = {
    GET_USER: "GET_USER",
    SAVE_USER: "SAVE_USER",
    CLEAR_USER: "CLEAR_USER",
    SHOW_LOGIN: "SHOW_LOGIN",
    HIDE_LOGIN: "HIDE_LOGIN",
    SHOW_REGISTER: "SHOW_REGISTER",
    HIDE_REGISTER: "HIDE_REGISTER",
    SHOW_FORGOTPASSWORD: "SHOW_FORGOTPASSWORD",
    HIDE_FORGOTPASSWORD: "HIDE_FORGOTPASSWORD",

    SHOW_FORM_LOGIN: "SHOW_FORM_LOGIN",
    HIDE_FORM_LOGIN: "HIDE_FORM_LOGIN",
    SHOW_FORM_REGISTER: "SHOW_FORM_REGISTER",
    HIDE_FORM_REGISTER: "HIDE_FORM_REGISTER",
    SHOW_FORM_FORGOT_PASSWORRD: "SHOW_FORM_FORGOT_PASSWORRD",
    HIDE_FORM_FORGOT_PASSWORRD: "HIDE_FORM_FORGOT_PASSWORRD",

    DEFAULT_SHOW_HIDE: "DEFAULT_SHOW_HIDE",
    SHOW_MODEL_OTP: "SHOW_MODEL_OTP",
    HIDE_MODEL_OTP: "HIDE_MODEL_OTP",
    HIDE_ALL: "HIDE_ALL"
}
export default TYPE_APP;