server:
  port: 8080
spring:
  main:
    banner-mode: off
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 47916404883-mi6ii5eh6fn82ulqdojrvjohg32fnkfr.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile
  application:
    name: project-website-learn-online
  datasource:
    url: jdbc:mysql://localhost:3306/learing-online
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
#    config mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenxuanmanh2992003@gmail.com
    password: txok lgxi wyei kode
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#            config login email

jwt:
  EXPIRATION_TIME: 86400000   # 1000 * 60 * 60 * 24 (1 ngày tính bằng mili giây)
  SECRETE: "YFBRaoJ7LxB2VB10cGWI5MIua1/xHvnpcOXDLIephhzpmpS2qPb+ijVeiCVhT0dK"
youtube:
  api_key: AIzaSyDsb5wa7fBTkow55HIvSVbrT1fBaS78b5o
  api_url: https://www.googleapis.com/youtube/v3/videos

order_step: 10
logging:
  level:
    root:
      warn
#root

#docker run --name mysql-8.0.36 -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -d mysql:8.0.36-debian